### ISSUE TITLE
Is it possible to run this locally?

### ISSUE THREAD

**Issue by cdharris** [Hacksore/overlayed-electron#1]
Hey @Hacksore , I stumbled across this project of yours while looking to integrate with Discord.

Is it possible to run this locally or (by looking at the auth flow) does this require approval which only you have on your hosted server? Any way to use this on my own account manually without approval?

**Comment by Hacksore** [comment]
@cdharris I actually have code on an uncommitted branch that includes a major refactor to use `discord-rpc` or at least my fork of it.

The whole auth flow has been redone to use a proper discord OAuth app rather than hacking at the [streamkit discord app](https://streamkit.discord.com/overlay). 

I've set up [auth.overlayed.dev](https://auth.overlayed.dev) to handle proper authentication. It's responsible for taking a redirect URL and generating an access/refresh token that can be used against the discord client. [example token request](https://discord.com/api/oauth2/authorize?client_id=905987126099836938&redirect_uri=https%3A%2F%2Fauth.overlayed.dev%2Foauth%2Fcallback&response_type=code&scope=rpc)

The code for the backend authentication is available at [Hacksore/overlayed-api](https://github.com/Hacksore/overlayed-api) if you want to understand that portion of it.

Hoping I can get around to publishing the client code soon so that you can take a look at it.

**Comment by Hacksore** [comment]
The branch is available https://github.com/Hacksore/overlayed/tree/discord-rpc-port

It's still very rough around the edge but it should work via `npm start`.

**Comment by cdharris** [comment]
This looks amazing!! appreciate your work and the quick response :) Hope to take a look soon! :pray:

**Comment by Hacksore** [comment]
I think it's ok to close this now as running should be easier with the new implementation that has been merged to master 😄
